### PR TITLE
Feature/79 excel import multi value columns

### PR DESCRIPTION
**Pull request by Michiel-s**

### CODE REVIEW

**Comment by Michiel-s** [comment]
Tested the solution with the project administration application.

The following sheet works. Here the former way of a binary table (rows 10 to 24) are replaced by a delimited multi value cell in column H.

image

**Comment by Michiel-s** [comment]
Related to #79

**Comment by stefjoosten** [comment]
@sjcjoosten and I did a first attempt in a separate branch, on commit Ampersandtarski/Prototype@326df095d5956ed5c74dca697770b4b091112610. This is yet to be tested...

**Comment by Michiel-s** [comment]
I'm deleting branch `multiple-atoms-per-cell-in-ExcellImporter` because the implementation of multi value columns was already merged to main by https://github.com/AmpersandTarski/prototype/commit/6a1b5bc04b572940d73ab4e116b04798862d9e0e

**Pull request merged**
